### PR TITLE
add props 'colors' and 'coloring'

### PR DESCRIPTION
**Pull request by dnassauer**
I have added the properties 'colors' and 'coloring', whereby 'colors' expects a list of colors and 'coloring' a coloring method ('random' or 'size').
Example:
<cloud :data="wordCount" :fontSizeMapper="fontSizeMapper" :colors="['#731964', '#a9218e', '#e6bedc']" coloring="size" />

### CODE REVIEW

**Comment by makeupsomething** [comment]
Thank you! Sorry for the slow reply. Il check this out and merge it tomorrow.

**Comment by dnassauer** [comment]
Thank you. Do you plan to merge this change into master and publish it on NPM?

**Comment by makeupsomething** [comment]
Sure, i was planning to update the structure of the project, but I guess i should publish your change first. Will do this week. Sorry for the delay on that and thank you again for your contribution.

**Comment by dnassauer** [comment]
no Problem. Thank you :)

**Pull request merged**
